import React, { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import {
  getIncidentByIdApi,
  getAuditLogsApi,
  updateIncidentApi,
  deleteIncidentApi,
} from '../api/incidents';
import { AuditLog, Incident, IncidentStatus } from '../types';
import { PriorityBadge, StatusBadge, CategoryBadge } from '../components/common/Badge';
import { AuditTimeline } from '../components/incidents/AuditTimeline';
import { UpdateIncidentModal } from '../components/incidents/UpdateIncidentModal';
import { AssignEngineerModal } from '../components/incidents/AssignEngineerModal';
import { ConfirmDialog } from '../components/common/ConfirmDialog';
import { ErrorBanner } from '../components/common/ErrorBanner';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
import { formatDate, formatRelativeTime, STATUS_CONFIG } from '../utils/formatters';
import {
  ArrowLeft,
  Calendar,
  Clock,
  User,
  UserCheck,
  Edit3,
  Trash2,
  PlayCircle,
  CheckCircle2,
  Archive,
  ArrowRight,
  ShieldCheck,
  History,
  AlertTriangle,
} from 'lucide-react';
import { ApiError } from '../api/client';

export const IncidentDetailPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { activeRole } = useAuth();
  const toast = useToast();

  const [incident, setIncident] = useState<Incident | null>(null);
  const [auditLogs, setAuditLogs] = useState<AuditLog[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState<any>(null);

  const [isEditModalOpen, setIsEditModalOpen] = useState<boolean>(false);
  const [isAssignModalOpen, setIsAssignModalOpen] = useState<boolean>(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState<boolean>(false);
  const [isDeleting, setIsDeleting] = useState<boolean>(false);
  const [isTransitioning, setIsTransitioning] = useState<boolean>(false);

  const fetchDetails = useCallback(async () => {
    if (!id) return;
    setError(null);
    try {
      const [inc, logs] = await Promise.all([
        getIncidentByIdApi(id),
        getAuditLogsApi(id).catch(() => [] as AuditLog[]),
      ]);
      setIncident(inc);
      setAuditLogs(logs || []);
    } catch (err: any) {
      console.error('Failed to fetch incident details', err);
      setError(err);
    } finally {
      setIsLoading(false);
    }
  }, [id]);

  useEffect(() => {
    fetchDetails();
  }, [fetchDetails]);

  const canEdit = activeRole === 'ADMIN' || activeRole === 'ENGINEER';
  const canAssign = activeRole === 'ADMIN' || activeRole === 'ENGINEER';
  const canDelete = activeRole === 'ADMIN';

  const handleQuickTransition = async (nextStatus: IncidentStatus) => {
    if (!incident) return;
    setIsTransitioning(true);
    try {
      const updated = await updateIncidentApi(incident.id, {
        status: nextStatus,
      });
      toast.success('Status Transitioned', `Incident moved to ${nextStatus}`);
      setIncident(updated);
      // Re-fetch audit logs to include the new audit log generated by backend
      const logs = await getAuditLogsApi(incident.id);
      setAuditLogs(logs);
    } catch (err: any) {
      console.error('Transition error', err);
      if (err instanceof ApiError) {
        if (err.status === 409) {
          toast.error('Invalid Transition', 'Backend rejected invalid lifecycle progression.');
        } else if (err.status === 403) {
          toast.error('Access Denied (403)', 'Only ENGINEER and ADMIN roles are authorized to transition status.');
        } else {
          toast.error('Transition Failed', err.message);
        }
      } else {
        toast.error('Transition Failed', err.message);
      }
    } finally {
      setIsTransitioning(false);
    }
  };

  const handleDelete = async () => {
    if (!incident) return;
    setIsDeleting(true);
    try {
      await deleteIncidentApi(incident.id);
      toast.success('Incident Deleted', `Incident #${incident.id.slice(-6)} removed.`);
      navigate('/incidents');
    } catch (err: any) {
      toast.error('Delete Failed', err.message);
      setIsDeleting(false);
    }
  };

  if (isLoading) {
    return (
      <div className="space-y-6 max-w-5xl mx-auto py-4">
        <div className="h-6 w-32 bg-slate-800 rounded animate-pulse" />
        <div className="h-40 bg-slate-900 border border-slate-800 rounded-2xl animate-pulse" />
        <div className="h-72 bg-slate-900 border border-slate-800 rounded-2xl animate-pulse" />
      </div>
    );
  }

  if (error || !incident) {
    return (
      <div className="max-w-3xl mx-auto py-12 space-y-4">
        <Link
          to="/incidents"
          className="inline-flex items-center gap-1.5 text-xs text-slate-400 hover:text-white"
        >
          <ArrowLeft className="w-3.5 h-3.5" /> Back to Queue
        </Link>
        <ErrorBanner
          error={error || 'Incident not found or inaccessible.'}
          onRetry={fetchDetails}
        />
      </div>
    );
  }

  // Lifecycle steps
  const steps: IncidentStatus[] = ['OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'];
  const currentStepIndex = steps.indexOf(incident.status);

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      {/* Back link & Actions bar */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 pb-2 border-b border-slate-800/80">
        <div className="flex items-center gap-2">
          <Link
            to="/incidents"
            className="p-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-400 hover:text-white transition-colors border border-slate-800"
          >
            <ArrowLeft className="w-4 h-4" />
          </Link>
          <div>
            <div className="flex items-center gap-2">
              <span className="text-xs font-mono text-indigo-400 font-bold">
                INCIDENT #{incident.id.slice(-6)}
              </span>
              <span className="text-slate-600">•</span>
              <PriorityBadge priority={incident.priority} size="sm" />
              <StatusBadge status={incident.status} size="sm" />
            </div>
            <h1 className="text-lg sm:text-xl font-extrabold text-white tracking-tight mt-0.5">
              {incident.title}
            </h1>
          </div>
        </div>

        {/* Primary Action Buttons */}
        <div className="flex flex-wrap items-center gap-2">
          {canEdit && (
            <button
              onClick={() => setIsEditModalOpen(true)}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-slate-200 bg-slate-900 hover:bg-slate-800 border border-slate-700/80 rounded-xl transition-colors"
            >
              <Edit3 className="w-3.5 h-3.5 text-slate-400" />
              <span>Edit Details</span>
            </button>
          )}

          {canAssign && (
            <button
              onClick={() => setIsAssignModalOpen(true)}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-white bg-indigo-600 hover:bg-indigo-500 rounded-xl transition-colors shadow-sm shadow-indigo-950/40"
            >
              <UserCheck className="w-3.5 h-3.5" />
              <span>Assign</span>
            </button>
          )}

          {canDelete && (
            <button
              onClick={() => setIsDeleteDialogOpen(true)}
              className="p-2 text-slate-400 hover:text-rose-400 hover:bg-rose-950/40 rounded-xl border border-transparent hover:border-rose-500/30 transition-colors"
              title="Delete Incident (Admin)"
            >
              <Trash2 className="w-4 h-4" />
            </button>
          )}
        </div>
      </div>

      {/* Lifecycle Progress Bar */}
      <div className="p-5 rounded-2xl bg-slate-900/90 border border-slate-800/90 shadow-sm space-y-3">
        <div className="flex items-center justify-between">
          <span className="text-xs font-semibold text-slate-300">Incident State Lifecycle</span>
          <span className="text-[11px] font-mono text-slate-400">
            Current Stage: <strong className="text-white">{incident.status}</strong>
          </span>
        </div>

        {/* Stepper visuals */}
        <div className="grid grid-cols-4 gap-2 pt-2">
          {steps.map((st, idx) => {
            const isCompleted = idx < currentStepIndex;
            const isCurrent = idx === currentStepIndex;
            const conf = STATUS_CONFIG[st];

            return (
              <div
                key={st}
                className={`p-3 rounded-xl border text-center transition-all ${
                  isCurrent
                    ? `${conf.border} ${conf.bg} ring-1 ring-indigo-500/40`
                    : isCompleted
                    ? 'bg-slate-950/80 border-slate-800 text-slate-400'
                    : 'bg-slate-950/40 border-slate-900 text-slate-600'
                }`}
              >
                <div className="text-[10px] font-mono text-slate-500 mb-0.5">Stage {idx + 1}</div>
                <div
                  className={`text-xs font-bold tracking-tight ${
                    isCurrent ? 'text-white' : isCompleted ? 'text-slate-300' : 'text-slate-600'
                  }`}
                >
                  {conf.label}
                </div>
              </div>
            );
          })}
        </div>

        {/* Quick Transition Triggers */}
        {canEdit && (
          <div className="flex flex-wrap items-center gap-2 pt-3 border-t border-slate-800/80">
            <span className="text-xs text-slate-400 mr-1">Available Transitions:</span>
            {incident.status === 'OPEN' && (
              <button
                onClick={() => handleQuickTransition('IN_PROGRESS')}
                disabled={isTransitioning}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-amber-600 hover:bg-amber-500 text-white rounded-lg text-xs font-semibold transition-colors disabled:opacity-50"
              >
                <PlayCircle className="w-3.5 h-3.5" />
                <span>Move to In Progress</span>
              </button>
            )}

            {incident.status === 'IN_PROGRESS' && (
              <button
                onClick={() => handleQuickTransition('RESOLVED')}
                disabled={isTransitioning}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg text-xs font-semibold transition-colors disabled:opacity-50"
              >
                <CheckCircle2 className="w-3.5 h-3.5" />
                <span>Mark as Resolved</span>
              </button>
            )}

            {incident.status === 'RESOLVED' && (
              <button
                onClick={() => handleQuickTransition('CLOSED')}
                disabled={isTransitioning}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-slate-700 hover:bg-slate-600 text-white rounded-lg text-xs font-semibold transition-colors disabled:opacity-50"
              >
                <Archive className="w-3.5 h-3.5" />
                <span>Close Ticket</span>
              </button>
            )}

            {incident.status === 'CLOSED' && (
              <span className="text-xs text-slate-500 italic">
                Ticket is closed. Final state reached.
              </span>
            )}
          </div>
        )}
      </div>

      {/* Grid: Details & Metadata + Audit Timeline */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column: Description & Metadata */}
        <div className="lg:col-span-2 space-y-6">
          {/* Description Card */}
          <div className="p-5 rounded-2xl bg-slate-900/90 border border-slate-800/90 shadow-sm space-y-4">
            <h3 className="text-sm font-bold text-white tracking-tight">Symptoms &amp; Description</h3>
            <div className="text-sm text-slate-300 leading-relaxed whitespace-pre-wrap bg-slate-950/60 p-4 rounded-xl border border-slate-800/80 font-sans">
              {incident.description || 'No detailed symptoms provided.'}
            </div>

            {/* Context meta badges */}
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 pt-2">
              <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
                <span className="text-[11px] text-slate-400 block mb-1">Service Domain</span>
                <CategoryBadge category={incident.category} />
              </div>
              <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
                <span className="text-[11px] text-slate-400 block mb-1">Assigned Engineer</span>
                <div className="text-xs font-semibold text-white font-mono truncate">
                  {incident.assignedTo || <span className="text-slate-500 italic">Unassigned</span>}
                </div>
              </div>
              <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
                <span className="text-[11px] text-slate-400 block mb-1">Reported By</span>
                <div className="text-xs font-semibold text-white font-mono truncate">
                  {incident.reportedBy || <span className="text-slate-500 italic">Unspecified</span>}
                </div>
              </div>
            </div>
          </div>

          {/* Audit History Card */}
          <div className="p-5 rounded-2xl bg-slate-900/90 border border-slate-800/90 shadow-sm space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-sm font-bold text-white tracking-tight flex items-center gap-2">
                  <History className="w-4 h-4 text-indigo-400" />
                  <span>Audit History Timeline</span>
                </h3>
                <p className="text-xs text-slate-400">
                  Real audit log generated by Spring Boot controller
                </p>
              </div>
              <span className="text-xs font-mono text-slate-400 bg-slate-800 px-2 py-0.5 rounded">
                {auditLogs.length} Events
              </span>
            </div>

            <AuditTimeline logs={auditLogs} />
          </div>
        </div>

        {/* Right Column: Key Details Sidebar */}
        <div className="space-y-5">
          <div className="p-5 rounded-2xl bg-slate-900/90 border border-slate-800/90 shadow-sm space-y-4">
            <h3 className="text-sm font-bold text-white tracking-tight">Ticket Metadata</h3>

            <div className="space-y-3 text-xs divide-y divide-slate-800/60">
              <div className="flex items-center justify-between pt-2">
                <span className="text-slate-400">Database ID:</span>
                <span className="font-mono text-slate-300 select-all">{incident.id}</span>
              </div>

              <div className="flex items-center justify-between pt-2">
                <span className="text-slate-400">Created:</span>
                <span className="font-mono text-slate-300" title={incident.createdAt}>
                  {formatDate(incident.createdAt)}
                </span>
              </div>

              <div className="flex items-center justify-between pt-2">
                <span className="text-slate-400">Last Modified:</span>
                <span className="font-mono text-slate-300" title={incident.updatedAt}>
                  {formatDate(incident.updatedAt)}
                </span>
              </div>

              <div className="flex items-center justify-between pt-2">
                <span className="text-slate-400">Age:</span>
                <span className="font-mono text-slate-300">
                  {formatRelativeTime(incident.createdAt)}
                </span>
              </div>
            </div>
          </div>

          {/* Quick Guidance Box */}
          <div className="p-4 rounded-2xl bg-slate-900/50 border border-slate-800 text-xs text-slate-400 space-y-2">
            <div className="font-semibold text-white flex items-center gap-1.5">
              <ShieldCheck className="w-4 h-4 text-indigo-400" />
              <span>Role Permissions Guidance</span>
            </div>
            <p className="text-[11px] leading-relaxed text-slate-400">
              Actions in IIMS are verified server-side against the Spring Security context.
              If an operation returns HTTP 403, your account does not currently hold the required role on the backend.
            </p>
          </div>
        </div>
      </div>

      {/* Modals */}
      <UpdateIncidentModal
        isOpen={isEditModalOpen}
        onClose={() => setIsEditModalOpen(false)}
        incident={incident}
        onSuccess={(updated) => {
          setIncident(updated);
          fetchDetails();
        }}
      />

      <AssignEngineerModal
        isOpen={isAssignModalOpen}
        onClose={() => setIsAssignModalOpen(false)}
        incident={incident}
        onSuccess={(updated) => {
          setIncident(updated);
          fetchDetails();
        }}
      />

      <ConfirmDialog
        isOpen={isDeleteDialogOpen}
        onClose={() => setIsDeleteDialogOpen(false)}
        onConfirm={handleDelete}
        title="Delete Incident"
        message={`Are you sure you want to permanently delete incident #${incident.id.slice(-6)}?`}
        confirmText="Delete Ticket"
        cancelText="Cancel"
        isDangerous={true}
        isLoading={isDeleting}
      />
    </div>
  );
};
